import { updateTuitionPaymentSchedule } from "@/actions/App/Http/Controllers/AdministratorSystemManagementController";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useForm } from "@inertiajs/react";
import { Calculator, Info, Loader2, Save } from "lucide-react";
import { toast } from "sonner";

import SystemManagementLayout from "./layout";
import type { SystemManagementPageProps, TuitionPaymentScheduleProfile, TuitionPaymentScheduleSettings } from "./types";

const studentTypes = [
    { value: "college", label: "College" },
    { value: "shs", label: "Senior High School" },
    { value: "tesda", label: "TESDA" },
    { value: "dhrt", label: "DHRT" },
] as const;
const paymentTerms = ["prelim", "midterm", "finals"] as const;

export default function TuitionPaymentSchedulePage({ user, access, tuition_payment_schedule_settings: settings }: SystemManagementPageProps) {
    const form = useForm<TuitionPaymentScheduleSettings>(settings);

    const setProfile = (studentType: keyof TuitionPaymentScheduleSettings["profiles"], profile: TuitionPaymentScheduleProfile) => {
        form.setData("profiles", { ...form.data.profiles, [studentType]: profile });
    };

    const submit = () => {
        form.put(updateTuitionPaymentSchedule.url(), {
            preserveScroll: true,
            onSuccess: () => toast.success("Tuition payment schedule updated."),
            onError: () => toast.error("Review the payment schedule values."),
        });
    };

    return (
        <SystemManagementLayout
            user={user}
            access={access}
            activeSection="tuition_payment_schedule"
            heading="Tuition Payment Schedule"
            description="Define how enrollment balances are divided into Prelim, Midterm, and Finals amounts."
        >
            <Alert>
                <Info className="size-4" />
                <AlertTitle>Existing schedules stay unchanged</AlertTitle>
                <AlertDescription>New rules apply when a schedule is generated or explicitly regenerated by Finance.</AlertDescription>
            </Alert>

            <Tabs defaultValue="college">
                <TabsList className="h-auto flex-wrap justify-start">
                    {studentTypes.map((type) => (
                        <TabsTrigger key={type.value} value={type.value}>
                            {type.label}
                        </TabsTrigger>
                    ))}
                </TabsList>

                {studentTypes.map((type) => {
                    const profile = form.data.profiles[type.value];
                    const percentageTotal = profile.percentages.prelim + profile.percentages.midterm + profile.percentages.finals;

                    return (
                        <TabsContent key={type.value} value={type.value} className="mt-5">
                            <Card>
                                <CardHeader className="flex-row items-start justify-between gap-4">
                                    <div>
                                        <CardTitle className="flex items-center gap-2">
                                            <Calculator className="size-5" />
                                            {type.label} installment rule
                                        </CardTitle>
                                        <CardDescription className="mt-1">
                                            Choose which terms are rounded and which term receives the exact remainder.
                                        </CardDescription>
                                    </div>
                                    <div className="flex items-center gap-3">
                                        <Label htmlFor={`${type.value}-enabled`}>Enabled</Label>
                                        <Switch
                                            id={`${type.value}-enabled`}
                                            checked={profile.enabled}
                                            onCheckedChange={(enabled) => setProfile(type.value, { ...profile, enabled })}
                                            disabled={!access.sections.tuition_payment_schedule?.can_update}
                                        />
                                    </div>
                                </CardHeader>
                                <CardContent className="space-y-6">
                                    <div className="grid gap-4 sm:grid-cols-3">
                                        {paymentTerms.map((term) => (
                                            <div key={term} className="space-y-2">
                                                <Label htmlFor={`${type.value}-${term}`}>{term[0].toUpperCase() + term.slice(1)} percentage</Label>
                                                <div className="relative">
                                                    <Input
                                                        id={`${type.value}-${term}`}
                                                        type="number"
                                                        min="0"
                                                        max="100"
                                                        step="0.01"
                                                        value={profile.percentages[term]}
                                                        onChange={(event) =>
                                                            setProfile(type.value, {
                                                                ...profile,
                                                                percentages: { ...profile.percentages, [term]: Number(event.target.value) },
                                                            })
                                                        }
                                                        className="pr-8 tabular-nums"
                                                    />
                                                    <span className="text-muted-foreground pointer-events-none absolute top-1/2 right-3 -translate-y-1/2 text-sm">
                                                        %
                                                    </span>
                                                </div>
                                            </div>
                                        ))}
                                    </div>

                                    <div className="grid gap-4 md:grid-cols-2">
                                        <div className="space-y-3 rounded-lg border p-4">
                                            <div>
                                                <Label>Rounded terms</Label>
                                                <p className="text-muted-foreground mt-1 text-xs">
                                                    Selected terms use the increment and method below. The remainder term always stays exact.
                                                </p>
                                            </div>
                                            <div className="flex flex-wrap gap-4">
                                                {paymentTerms.map((term) => {
                                                    const checked = profile.rounded_terms.includes(term);
                                                    const isRemainder = profile.remainder_term === term;

                                                    return (
                                                        <label key={term} className="flex items-center gap-2 text-sm capitalize">
                                                            <Checkbox
                                                                checked={checked}
                                                                disabled={isRemainder || !access.sections.tuition_payment_schedule?.can_update}
                                                                onCheckedChange={(value) =>
                                                                    setProfile(type.value, {
                                                                        ...profile,
                                                                        rounded_terms: value
                                                                            ? [...profile.rounded_terms, term]
                                                                            : profile.rounded_terms.filter((item) => item !== term),
                                                                    })
                                                                }
                                                            />
                                                            {term}
                                                        </label>
                                                    );
                                                })}
                                            </div>
                                        </div>
                                        <div className="space-y-2 rounded-lg border p-4">
                                            <Label>Exact remainder term</Label>
                                            <Select
                                                value={profile.remainder_term}
                                                onValueChange={(value) => {
                                                    const remainder = value as TuitionPaymentScheduleProfile["remainder_term"];
                                                    setProfile(type.value, {
                                                        ...profile,
                                                        remainder_term: remainder,
                                                        rounded_terms: profile.rounded_terms.filter((term) => term !== remainder),
                                                    });
                                                }}
                                            >
                                                <SelectTrigger>
                                                    <SelectValue />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    {paymentTerms.map((term) => (
                                                        <SelectItem key={term} value={term} className="capitalize">
                                                            {term}
                                                        </SelectItem>
                                                    ))}
                                                </SelectContent>
                                            </Select>
                                            <p className="text-muted-foreground text-xs">
                                                Receives all remaining pesos and centavos after the other terms are calculated.
                                            </p>
                                        </div>
                                    </div>

                                    <div className="grid gap-4 md:grid-cols-3">
                                        <div className="space-y-2">
                                            <Label htmlFor={`${type.value}-increment`}>Rounding increment</Label>
                                            <Input
                                                id={`${type.value}-increment`}
                                                type="number"
                                                min="0.01"
                                                step="0.01"
                                                value={profile.rounding_increment}
                                                onChange={(event) =>
                                                    setProfile(type.value, { ...profile, rounding_increment: Number(event.target.value) })
                                                }
                                                className="tabular-nums"
                                            />
                                            <p className="text-muted-foreground text-xs">Use ₱100 to remove tens and ones.</p>
                                        </div>
                                        <div className="space-y-2">
                                            <Label>Rounding method</Label>
                                            <Select
                                                value={profile.rounding_mode}
                                                onValueChange={(value) =>
                                                    setProfile(type.value, {
                                                        ...profile,
                                                        rounding_mode: value as TuitionPaymentScheduleProfile["rounding_mode"],
                                                    })
                                                }
                                            >
                                                <SelectTrigger>
                                                    <SelectValue />
                                                </SelectTrigger>
                                                <SelectContent>
                                                    <SelectItem value="nearest">Nearest increment</SelectItem>
                                                    <SelectItem value="down">Always round down</SelectItem>
                                                    <SelectItem value="up">Always round up</SelectItem>
                                                </SelectContent>
                                            </Select>
                                        </div>
                                        <div className="bg-muted/35 rounded-lg border p-4">
                                            <p className="text-muted-foreground text-xs font-medium tracking-wide uppercase">Rule check</p>
                                            <p
                                                className={`mt-2 text-lg font-semibold tabular-nums ${percentageTotal === 100 ? "text-emerald-600" : "text-destructive"}`}
                                            >
                                                {percentageTotal}% total
                                            </p>
                                            <p className="text-muted-foreground mt-1 text-xs capitalize">
                                                {profile.remainder_term} receives all rounding remainder.
                                            </p>
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>
                        </TabsContent>
                    );
                })}
            </Tabs>

            <div className="flex justify-end border-t pt-4">
                <Button onClick={submit} disabled={form.processing || !access.sections.tuition_payment_schedule?.can_update}>
                    {form.processing ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
                    Save schedule settings
                </Button>
            </div>
        </SystemManagementLayout>
    );
}
