"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _admin_administrators_curriculum_programs from './admin-administrators-curriculum-programs.bones.json'
import _admin_administrators_audit_logs_index from './admin-administrators-audit-logs-index.bones.json'
import _admin_administrators_classes_create from './admin-administrators-classes-create.bones.json'
import _admin_administrators_classes_index from './admin-administrators-classes-index.bones.json'
import _admin_administrators_classes_show from './admin-administrators-classes-show.bones.json'
import _admin_administrators_curriculum_programs_index from './admin-administrators-curriculum-programs-index.bones.json'
import _admin_administrators_curriculum_programs_show from './admin-administrators-curriculum-programs-show.bones.json'
import _admin_administrators_dashboard from './admin-administrators-dashboard.bones.json'
import _admin_administrators_departments_edit from './admin-administrators-departments-edit.bones.json'
import _admin_administrators_departments_index from './admin-administrators-departments-index.bones.json'
import _admin_administrators_enrollments_applicants from './admin-administrators-enrollments-applicants.bones.json'
import _admin_administrators_enrollments_assessment_preview from './admin-administrators-enrollments-assessment-preview.bones.json'
import _admin_administrators_enrollments_create from './admin-administrators-enrollments-create.bones.json'
import _admin_administrators_enrollments_edit from './admin-administrators-enrollments-edit.bones.json'
import _admin_administrators_enrollments_index from './admin-administrators-enrollments-index.bones.json'
import _admin_administrators_enrollments_show from './admin-administrators-enrollments-show.bones.json'
import _admin_administrators_faculties_create from './admin-administrators-faculties-create.bones.json'
import _admin_administrators_faculties_edit from './admin-administrators-faculties-edit.bones.json'
import _admin_administrators_faculties_index from './admin-administrators-faculties-index.bones.json'
import _admin_administrators_faculties_show from './admin-administrators-faculties-show.bones.json'
import _admin_administrators_feature_toggles_index from './admin-administrators-feature-toggles-index.bones.json'
import _admin_administrators_finance_create_payment from './admin-administrators-finance-create-payment.bones.json'
import _admin_administrators_finance_dashboard from './admin-administrators-finance-dashboard.bones.json'
import _admin_administrators_finance_invoices from './admin-administrators-finance-invoices.bones.json'
import _admin_administrators_finance_payments from './admin-administrators-finance-payments.bones.json'
import _admin_administrators_finance_receipt from './admin-administrators-finance-receipt.bones.json'
import _admin_administrators_finance_reports from './admin-administrators-finance-reports.bones.json'
import _admin_administrators_finance_tuition_adjustment_spreadsheet_import from './admin-administrators-finance-tuition-adjustment-spreadsheet-import.bones.json'
import _admin_administrators_finance_tuition_adjustments from './admin-administrators-finance-tuition-adjustments.bones.json'
import _admin_administrators_finance_tuition_update_requests_index from './admin-administrators-finance-tuition-update-requests-index.bones.json'
import _admin_administrators_finance_tuition_update_requests_show from './admin-administrators-finance-tuition-update-requests-show.bones.json'
import _admin_administrators_help_index from './admin-administrators-help-index.bones.json'
import _admin_administrators_help_show from './admin-administrators-help-show.bones.json'
import _admin_administrators_inventory_borrowings_edit from './admin-administrators-inventory-borrowings-edit.bones.json'
import _admin_administrators_inventory_borrowings_index from './admin-administrators-inventory-borrowings-index.bones.json'
import _admin_administrators_inventory_index from './admin-administrators-inventory-index.bones.json'
import _admin_administrators_inventory_items_edit from './admin-administrators-inventory-items-edit.bones.json'
import _admin_administrators_inventory_items_index from './admin-administrators-inventory-items-index.bones.json'
import _admin_administrators_inventory_ledger_index from './admin-administrators-inventory-ledger-index.bones.json'
import _admin_administrators_library_authors_edit from './admin-administrators-library-authors-edit.bones.json'
import _admin_administrators_library_authors_index from './admin-administrators-library-authors-index.bones.json'
import _admin_administrators_library_books_edit from './admin-administrators-library-books-edit.bones.json'
import _admin_administrators_library_books_index from './admin-administrators-library-books-index.bones.json'
import _admin_administrators_library_borrow_records_edit from './admin-administrators-library-borrow-records-edit.bones.json'
import _admin_administrators_library_borrow_records_index from './admin-administrators-library-borrow-records-index.bones.json'
import _admin_administrators_library_categories_edit from './admin-administrators-library-categories-edit.bones.json'
import _admin_administrators_library_categories_index from './admin-administrators-library-categories-index.bones.json'
import _admin_administrators_library_index from './admin-administrators-library-index.bones.json'
import _admin_administrators_library_research_papers_edit from './admin-administrators-library-research-papers-edit.bones.json'
import _admin_administrators_library_research_papers_index from './admin-administrators-library-research-papers-index.bones.json'
import _admin_administrators_module_marketplace_index from './admin-administrators-module-marketplace-index.bones.json'
import _admin_administrators_registrar_analytics from './admin-administrators-registrar-analytics.bones.json'
import _admin_administrators_registrar_reports from './admin-administrators-registrar-reports.bones.json'
import _admin_administrators_roles_edit from './admin-administrators-roles-edit.bones.json'
import _admin_administrators_roles_index from './admin-administrators-roles-index.bones.json'
import _admin_administrators_scheduling_analytics from './admin-administrators-scheduling-analytics.bones.json'
import _admin_administrators_students_create from './admin-administrators-students-create.bones.json'
import _admin_administrators_students_documents_index from './admin-administrators-students-documents-index.bones.json'
import _admin_administrators_students_documents_list from './admin-administrators-students-documents-list.bones.json'
import _admin_administrators_students_edit from './admin-administrators-students-edit.bones.json'
import _admin_administrators_students_index from './admin-administrators-students-index.bones.json'
import _admin_administrators_students_show from './admin-administrators-students-show.bones.json'
import _admin_administrators_system_management_analytics from './admin-administrators-system-management-analytics.bones.json'
import _admin_administrators_system_management_api from './admin-administrators-system-management-api.bones.json'
import _admin_administrators_system_management_brand from './admin-administrators-system-management-brand.bones.json'
import _admin_administrators_system_management_enrollment_pipeline from './admin-administrators-system-management-enrollment-pipeline.bones.json'
import _admin_administrators_system_management_faculty_fields from './admin-administrators-system-management-faculty-fields.bones.json'
import _admin_administrators_system_management_finance_documents from './admin-administrators-system-management-finance-documents.bones.json'
import _admin_administrators_system_management_grading from './admin-administrators-system-management-grading.bones.json'
import _admin_administrators_system_management_identifiers from './admin-administrators-system-management-identifiers.bones.json'
import _admin_administrators_system_management_index from './admin-administrators-system-management-index.bones.json'
import _admin_administrators_system_management_mail from './admin-administrators-system-management-mail.bones.json'
import _admin_administrators_system_management_newsletter from './admin-administrators-system-management-newsletter.bones.json'
import _admin_administrators_system_management_notifications from './admin-administrators-system-management-notifications.bones.json'
import _admin_administrators_system_management_pulse from './admin-administrators-system-management-pulse.bones.json'
import _admin_administrators_system_management_school from './admin-administrators-system-management-school.bones.json'
import _admin_administrators_system_management_seo from './admin-administrators-system-management-seo.bones.json'
import _admin_administrators_system_management_socialite from './admin-administrators-system-management-socialite.bones.json'
import _admin_administrators_system_management_tuition_payment_schedule from './admin-administrators-system-management-tuition-payment-schedule.bones.json'
import _admin_administrators_users_create from './admin-administrators-users-create.bones.json'
import _admin_administrators_users_edit from './admin-administrators-users-edit.bones.json'
import _admin_administrators_users_index from './admin-administrators-users-index.bones.json'
import _admin_announcement_index from './admin-announcement-index.bones.json'
import _admin_notificationcenter_index from './admin-notificationcenter-index.bones.json'
import _admin_notifications_index from './admin-notifications-index.bones.json'
import _admin_profile from './admin-profile.bones.json'

configureBoneyard({"color":"rgba(120, 120, 120, 0.16)","darkColor":"rgba(255, 255, 255, 0.08)","animate":"shimmer","shimmerColor":"rgba(255, 255, 255, 0.48)","darkShimmerColor":"rgba(255, 255, 255, 0.14)","speed":"2s","transition":300})

registerBones({
  "admin-administrators-curriculum-programs": _admin_administrators_curriculum_programs,
  "admin-administrators-audit-logs-index": _admin_administrators_audit_logs_index,
  "admin-administrators-classes-create": _admin_administrators_classes_create,
  "admin-administrators-classes-index": _admin_administrators_classes_index,
  "admin-administrators-classes-show": _admin_administrators_classes_show,
  "admin-administrators-curriculum-programs-index": _admin_administrators_curriculum_programs_index,
  "admin-administrators-curriculum-programs-show": _admin_administrators_curriculum_programs_show,
  "admin-administrators-dashboard": _admin_administrators_dashboard,
  "admin-administrators-departments-edit": _admin_administrators_departments_edit,
  "admin-administrators-departments-index": _admin_administrators_departments_index,
  "admin-administrators-enrollments-applicants": _admin_administrators_enrollments_applicants,
  "admin-administrators-enrollments-assessment-preview": _admin_administrators_enrollments_assessment_preview,
  "admin-administrators-enrollments-create": _admin_administrators_enrollments_create,
  "admin-administrators-enrollments-edit": _admin_administrators_enrollments_edit,
  "admin-administrators-enrollments-index": _admin_administrators_enrollments_index,
  "admin-administrators-enrollments-show": _admin_administrators_enrollments_show,
  "admin-administrators-faculties-create": _admin_administrators_faculties_create,
  "admin-administrators-faculties-edit": _admin_administrators_faculties_edit,
  "admin-administrators-faculties-index": _admin_administrators_faculties_index,
  "admin-administrators-faculties-show": _admin_administrators_faculties_show,
  "admin-administrators-feature-toggles-index": _admin_administrators_feature_toggles_index,
  "admin-administrators-finance-create-payment": _admin_administrators_finance_create_payment,
  "admin-administrators-finance-dashboard": _admin_administrators_finance_dashboard,
  "admin-administrators-finance-invoices": _admin_administrators_finance_invoices,
  "admin-administrators-finance-payments": _admin_administrators_finance_payments,
  "admin-administrators-finance-receipt": _admin_administrators_finance_receipt,
  "admin-administrators-finance-reports": _admin_administrators_finance_reports,
  "admin-administrators-finance-tuition-adjustment-spreadsheet-import": _admin_administrators_finance_tuition_adjustment_spreadsheet_import,
  "admin-administrators-finance-tuition-adjustments": _admin_administrators_finance_tuition_adjustments,
  "admin-administrators-finance-tuition-update-requests-index": _admin_administrators_finance_tuition_update_requests_index,
  "admin-administrators-finance-tuition-update-requests-show": _admin_administrators_finance_tuition_update_requests_show,
  "admin-administrators-help-index": _admin_administrators_help_index,
  "admin-administrators-help-show": _admin_administrators_help_show,
  "admin-administrators-inventory-borrowings-edit": _admin_administrators_inventory_borrowings_edit,
  "admin-administrators-inventory-borrowings-index": _admin_administrators_inventory_borrowings_index,
  "admin-administrators-inventory-index": _admin_administrators_inventory_index,
  "admin-administrators-inventory-items-edit": _admin_administrators_inventory_items_edit,
  "admin-administrators-inventory-items-index": _admin_administrators_inventory_items_index,
  "admin-administrators-inventory-ledger-index": _admin_administrators_inventory_ledger_index,
  "admin-administrators-library-authors-edit": _admin_administrators_library_authors_edit,
  "admin-administrators-library-authors-index": _admin_administrators_library_authors_index,
  "admin-administrators-library-books-edit": _admin_administrators_library_books_edit,
  "admin-administrators-library-books-index": _admin_administrators_library_books_index,
  "admin-administrators-library-borrow-records-edit": _admin_administrators_library_borrow_records_edit,
  "admin-administrators-library-borrow-records-index": _admin_administrators_library_borrow_records_index,
  "admin-administrators-library-categories-edit": _admin_administrators_library_categories_edit,
  "admin-administrators-library-categories-index": _admin_administrators_library_categories_index,
  "admin-administrators-library-index": _admin_administrators_library_index,
  "admin-administrators-library-research-papers-edit": _admin_administrators_library_research_papers_edit,
  "admin-administrators-library-research-papers-index": _admin_administrators_library_research_papers_index,
  "admin-administrators-module-marketplace-index": _admin_administrators_module_marketplace_index,
  "admin-administrators-registrar-analytics": _admin_administrators_registrar_analytics,
  "admin-administrators-registrar-reports": _admin_administrators_registrar_reports,
  "admin-administrators-roles-edit": _admin_administrators_roles_edit,
  "admin-administrators-roles-index": _admin_administrators_roles_index,
  "admin-administrators-scheduling-analytics": _admin_administrators_scheduling_analytics,
  "admin-administrators-students-create": _admin_administrators_students_create,
  "admin-administrators-students-documents-index": _admin_administrators_students_documents_index,
  "admin-administrators-students-documents-list": _admin_administrators_students_documents_list,
  "admin-administrators-students-edit": _admin_administrators_students_edit,
  "admin-administrators-students-index": _admin_administrators_students_index,
  "admin-administrators-students-show": _admin_administrators_students_show,
  "admin-administrators-system-management-analytics": _admin_administrators_system_management_analytics,
  "admin-administrators-system-management-api": _admin_administrators_system_management_api,
  "admin-administrators-system-management-brand": _admin_administrators_system_management_brand,
  "admin-administrators-system-management-enrollment-pipeline": _admin_administrators_system_management_enrollment_pipeline,
  "admin-administrators-system-management-faculty-fields": _admin_administrators_system_management_faculty_fields,
  "admin-administrators-system-management-finance-documents": _admin_administrators_system_management_finance_documents,
  "admin-administrators-system-management-grading": _admin_administrators_system_management_grading,
  "admin-administrators-system-management-identifiers": _admin_administrators_system_management_identifiers,
  "admin-administrators-system-management-index": _admin_administrators_system_management_index,
  "admin-administrators-system-management-mail": _admin_administrators_system_management_mail,
  "admin-administrators-system-management-newsletter": _admin_administrators_system_management_newsletter,
  "admin-administrators-system-management-notifications": _admin_administrators_system_management_notifications,
  "admin-administrators-system-management-pulse": _admin_administrators_system_management_pulse,
  "admin-administrators-system-management-school": _admin_administrators_system_management_school,
  "admin-administrators-system-management-seo": _admin_administrators_system_management_seo,
  "admin-administrators-system-management-socialite": _admin_administrators_system_management_socialite,
  "admin-administrators-system-management-tuition-payment-schedule": _admin_administrators_system_management_tuition_payment_schedule,
  "admin-administrators-users-create": _admin_administrators_users_create,
  "admin-administrators-users-edit": _admin_administrators_users_edit,
  "admin-administrators-users-index": _admin_administrators_users_index,
  "admin-announcement-index": _admin_announcement_index,
  "admin-notificationcenter-index": _admin_notificationcenter_index,
  "admin-notifications-index": _admin_notifications_index,
  "admin-profile": _admin_profile,
})
