version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Etc/UTC
    groups:
      docker-base-images:
        patterns:
          - "*"
