version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
      time: "03:30"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    groups:
      koakademy-modules:
        patterns:
          - "koakademy/*"
    commit-message:
      prefix: "build(modules)"
      include: "scope"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Etc/UTC
    groups:
      docker-base-images:
        patterns:
          - "*"
