[program:station-default]
process_name = %(program_name)s_%(process_num)s
command = php /app/artisan station:work redis --queue=default,assessments --workers=3 --memory=512 --timeout=60 --tries=1
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 120

[program:station-pdf]
process_name = %(program_name)s_%(process_num)s
command = php /app/artisan station:work redis-pdf --queue=pdf-generation --workers=2 --memory=2048 --timeout=3600 --tries=1
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 3660

[program:assessment-pdf]
process_name = %(program_name)s_%(process_num)02d
command = php /app/artisan queue:work %(ENV_ASSESSMENT_EXPORT_CONNECTION)s --queue=%(ENV_ASSESSMENT_EXPORT_QUEUE)s --sleep=1 --timeout=%(ENV_ASSESSMENT_EXPORT_WORKER_TIMEOUT)s --memory=%(ENV_ASSESSMENT_EXPORT_WORKER_MEMORY)s --max-time=3600
numprocs = %(ENV_ASSESSMENT_EXPORT_PROCESSES)s
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 1980

[program:assessment-events]
process_name = %(program_name)s_%(process_num)02d
command = php /app/artisan queue:work %(ENV_ASSESSMENT_EXPORT_CONNECTION)s --queue=%(ENV_ASSESSMENT_EXPORT_EVENT_QUEUE)s --sleep=1 --tries=3 --timeout=60 --memory=256 --max-time=3600
numprocs = %(ENV_ASSESSMENT_EXPORT_EVENT_PROCESSES)s
user = %(ENV_USER)s
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
stopsignal = TERM
stopwaitsecs = 120

[include]
files = /etc/supervisord.conf
