<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Chrome Path
    |--------------------------------------------------------------------------
    |
    | Path to the Chrome/Chromium binary. If not set, the service will try
    | to detect it automatically. Common paths for different environments:
    | - Ubuntu/Debian: /usr/bin/chromium-browser
    | - Arch Linux: /usr/bin/chromium
    | - Nix: /root/.nix-profile/bin/chromium
    | - Docker: /usr/bin/google-chrome-stable
    |
    */
    'chrome_path' => env('CHROME_BIN', env('CHROME_PATH', '/usr/bin/google-chrome-stable')),

    /*
    |--------------------------------------------------------------------------
    | Node Binary Path
    |--------------------------------------------------------------------------
    |
    | Path to the Node.js binary. If not set, the service will try to detect
    | it automatically.
    |
    */
    'node_binary_path' => env('NODE_BINARY_PATH', '/usr/bin/node'),

    /*
    |--------------------------------------------------------------------------
    | NPM Binary Path
    |--------------------------------------------------------------------------
    |
    | Path to the NPM binary. Use the system npm in the container.
    |
    */
    'npm_binary_path' => env('NPM_BINARY_PATH', '/usr/bin/npm'),

    /*
    |--------------------------------------------------------------------------
    | Temporary Directory
    |--------------------------------------------------------------------------
    |
    | Directory for temporary files generated by Browsershot.
    |
    */
    'temp_directory' => storage_path('app/browsershot-temp'),

    /*
    |--------------------------------------------------------------------------
    | Default Options
    |--------------------------------------------------------------------------
    |
    | Default options to apply to all Browsershot instances.
    |
    */
    'default_options' => [
        'noSandbox' => true,
        'disableWebSecurity' => true,
        'ignoreHttpsErrors' => true,
        'timeout' => 120,
        'disableGpu' => true,
        'disableDevShmUsage' => true,
        'disableSetuidSandbox' => true,
        'singleProcess' => true,
        // VM-compatible Chrome arguments (used by the service)
        'args' => [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
            '--disable-gpu',
            '--no-first-run',
            '--disable-background-timer-throttling',
            '--disable-backgrounding-occluded-windows',
            '--disable-renderer-backgrounding',
            '--disable-extensions',
            '--disable-web-security',
            '--disable-features=VizDisplayCompositor',
            '--disable-ipc-flooding-protection',
            '--headless=new',
            '--disable-crash-reporter',
            '--crash-dumps-dir=/tmp',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | PDF Options
    |--------------------------------------------------------------------------
    |
    | Default PDF generation options.
    |
    */
    'pdf_options' => [
        'format' => 'A4',
        'landscape' => false,
        'print_background' => true,
        'margin_top' => 10,
        'margin_bottom' => 10,
        'margin_left' => 10,
        'margin_right' => 10,
        'timeout' => 120,
    ],

    /*
    |--------------------------------------------------------------------------
    | Chrome Arguments - VM Compatible
    |--------------------------------------------------------------------------
    |
    | VM-compatible Chrome arguments based on working GenerateStudentListPdfJob.
    | These settings ensure PDF generation works reliably in virtual machines.
    |
    */
    'chrome_arguments' => [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu',
        '--no-first-run',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-renderer-backgrounding',
        '--disable-extensions',
        '--disable-web-security',
        '--disable-features=VizDisplayCompositor',
        '--disable-ipc-flooding-protection',
        '--headless=new',
        '--disable-crash-reporter',
        '--crash-dumps-dir=/tmp',
    ],
];
