<?php

declare(strict_types=1);

return [
    'force_on_login' => (bool) env('ONBOARDING_FORCE_ON_LOGIN', false),
    'experimental_feature_keys' => [
        'onboarding-faculty-toolkit',
        'onboarding-faculty-at-risk-alerts',
        'onboarding-faculty-assessments',
        'onboarding-faculty-inbox',
        'onboarding-faculty-office-hours',
        'onboarding-faculty-requests-approvals',
        'onboarding-faculty-insights',
        'onboarding-faculty-grades',
        'onboarding-faculty-attendance',
        'onboarding-faculty-resources',
        'onboarding-faculty-forms',
        'onboarding-faculty-developer-mode',
        'onboarding-student',
        'onboarding-student-dashboard',
        'onboarding-student-classes',
        'onboarding-student-tuition',
        'onboarding-student-schedule',
        'onboarding-student-announcements',
        'onboarding-student-settings',
        'onboarding-student-help',
        'onboarding-student-schedule',
        'onboarding-student-grades-preview',
        'onboarding-student-attendance-tracker',
        'onboarding-student-developer-mode',
    ],
    'experimental_features_roles' => [
        'onboarding-faculty-toolkit' => ['faculty'],
        'onboarding-faculty-at-risk-alerts' => ['faculty'],
        'onboarding-faculty-assessments' => ['faculty'],
        'onboarding-faculty-inbox' => ['faculty'],
        'onboarding-faculty-office-hours' => ['faculty'],
        'onboarding-faculty-requests-approvals' => ['faculty'],
        'onboarding-faculty-insights' => ['faculty'],
        'onboarding-faculty-grades' => ['faculty'],
        'onboarding-faculty-attendance' => ['faculty'],
        'onboarding-faculty-resources' => ['faculty'],
        'onboarding-faculty-forms' => ['faculty'],
        'onboarding-faculty-developer-mode' => ['faculty'],
        'onboarding-student' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-dashboard' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-classes' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-tuition' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-schedule' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-announcements' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-settings' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-help' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-schedule' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-grades-preview' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-attendance-tracker' => ['student', 'shs_student', 'graduate_student'],
        'onboarding-student-developer-mode' => ['student', 'shs_student', 'graduate_student'],
    ],
];
