<?php

declare(strict_types=1);

/**
 * Ziggy route manifest served to the front end.
 *
 * The application registers over a thousand named routes, but the front end only ever resolves
 * the names listed below. Shipping all of them cost roughly 134 KB of JSON in every page
 * payload, which was 93% of the administrator dashboard's; this list is around 30 KB.
 *
 * `only` is an allowlist of route NAMES, not uri patterns.
 *
 * The list is verified against the source by tests/Feature/ZiggyRouteManifestTest.php, which
 * greps resources/js for route() and routeName= calls plus the app/ routes that reach the front
 * end as Inertia props (queue hrefs, the desk switcher), and fails if any of them is missing
 * from here. Add the name in the same change that introduces the call, or the test will fail.
 *
 * Names reached through a dynamic `route(routeName)` in a data table are covered too: the test
 * reads those `routeName = "..."` defaults and props as well.
 */
return [
    'only' => [
        // administrators
        'administrators.announcements.destroy',
        'administrators.announcements.store',
        'administrators.announcements.update',
        'administrators.audit-logs.index',
        'administrators.classes.copy',
        'administrators.classes.create',
        'administrators.classes.destroy',
        'administrators.classes.edit',
        'administrators.classes.export-student-list',
        'administrators.classes.index',
        'administrators.classes.move-student',
        'administrators.classes.options.shs-strands',
        'administrators.classes.options.shs-subjects',
        'administrators.classes.options.subjects',
        'administrators.classes.show',
        'administrators.classes.store',
        'administrators.classes.update',
        'administrators.curriculum.authority-codes.search',
        'administrators.curriculum.code-authorities.store',
        'administrators.curriculum.code-authorities.template',
        'administrators.curriculum.code-authority-imports.confirm',
        'administrators.curriculum.code-authority-imports.store',
        'administrators.curriculum.programs.index',
        'administrators.curriculum.programs.subjects.destroy',
        'administrators.curriculum.programs.subjects.store',
        'administrators.curriculum.programs.subjects.update',
        'administrators.curriculum.programs.update',
        'administrators.departments.destroy',
        'administrators.departments.index',
        'administrators.departments.store',
        'administrators.departments.update',
        'administrators.desks.show',
        'administrators.enrollments.advance-pipeline-step',
        'administrators.enrollments.api.sections',
        'administrators.enrollments.api.student-details',
        'administrators.enrollments.api.students',
        'administrators.enrollments.api.subjects',
        'administrators.enrollments.applicants',
        'administrators.enrollments.applicants.notify-approval',
        'administrators.enrollments.assessment-preview',
        'administrators.enrollments.class-schedule-changes.notify',
        'administrators.enrollments.create',
        'administrators.enrollments.destroy',
        'administrators.enrollments.edit',
        'administrators.enrollments.enroll-class',
        'administrators.enrollments.force-destroy',
        'administrators.enrollments.index',
        'administrators.enrollments.quick-enroll',
        'administrators.enrollments.resend-assessment',
        'administrators.enrollments.restore',
        'administrators.enrollments.restore-subjects',
        'administrators.enrollments.retry-enrollment',
        'administrators.enrollments.scholarship.update',
        'administrators.enrollments.show',
        'administrators.enrollments.store',
        'administrators.enrollments.transactions.update',
        'administrators.enrollments.undo-cashier',
        'administrators.enrollments.undo-head-dept',
        'administrators.enrollments.update',
        'administrators.enrollments.verify-cashier',
        'administrators.enrollments.verify-head-dept',
        'administrators.faculties.assign-classes',
        'administrators.faculties.bulk.status',
        'administrators.faculties.classes.unassign',
        'administrators.faculties.create',
        'administrators.faculties.deadlines.store',
        'administrators.faculties.destroy',
        'administrators.faculties.edit',
        'administrators.faculties.imports.confirm',
        'administrators.faculties.imports.store',
        'administrators.faculties.imports.template',
        'administrators.faculties.index',
        'administrators.faculties.notice',
        'administrators.faculties.portal-account',
        'administrators.faculties.show',
        'administrators.faculties.store',
        'administrators.faculties.update',
        'administrators.faculties.update-id-number',
        'administrators.feature-toggles.activate-for-user',
        'administrators.feature-toggles.deactivate-for-user',
        'administrators.feature-toggles.index',
        'administrators.feature-toggles.overridden-users',
        'administrators.feature-toggles.purge-overrides',
        'administrators.feature-toggles.toggle',
        'administrators.finance.documents.download',
        'administrators.finance.index',
        'administrators.finance.invoices',
        'administrators.finance.payments',
        'administrators.finance.payments.batch.store',
        'administrators.finance.payments.create',
        'administrators.finance.payments.ledger.resolve',
        'administrators.finance.payments.show',
        'administrators.finance.reports',
        'administrators.finance.reports.cashier-performance',
        'administrators.finance.reports.collection',
        'administrators.finance.reports.daily-collection',
        'administrators.finance.reports.fully-paid',
        'administrators.finance.reports.outstanding-balances',
        'administrators.finance.reports.revenue-breakdown',
        'administrators.finance.reports.scholarship',
        'administrators.help-tickets.destroy',
        'administrators.help-tickets.index',
        'administrators.help-tickets.reply',
        'administrators.help-tickets.show',
        'administrators.help-tickets.update',
        'administrators.inventory.borrowings.create',
        'administrators.inventory.borrowings.destroy',
        'administrators.inventory.borrowings.edit',
        'administrators.inventory.borrowings.index',
        'administrators.inventory.borrowings.store',
        'administrators.inventory.borrowings.update',
        'administrators.inventory.items.create',
        'administrators.inventory.items.destroy',
        'administrators.inventory.items.edit',
        'administrators.inventory.items.index',
        'administrators.inventory.items.store',
        'administrators.inventory.items.update',
        'administrators.inventory.items.update-location',
        'administrators.inventory.ledger.index',
        'administrators.library.authors.create',
        'administrators.library.authors.destroy',
        'administrators.library.authors.edit',
        'administrators.library.authors.index',
        'administrators.library.authors.store',
        'administrators.library.authors.update',
        'administrators.library.books.bulk-destroy',
        'administrators.library.books.bulk-force-destroy',
        'administrators.library.books.destroy',
        'administrators.library.books.edit',
        'administrators.library.books.index',
        'administrators.library.borrow-records.create',
        'administrators.library.borrow-records.destroy',
        'administrators.library.borrow-records.edit',
        'administrators.library.borrow-records.index',
        'administrators.library.borrow-records.store',
        'administrators.library.borrow-records.update',
        'administrators.library.categories.create',
        'administrators.library.categories.destroy',
        'administrators.library.categories.edit',
        'administrators.library.categories.index',
        'administrators.library.categories.store',
        'administrators.library.categories.update',
        'administrators.library.research-papers.create',
        'administrators.library.research-papers.destroy',
        'administrators.library.research-papers.edit',
        'administrators.library.research-papers.index',
        'administrators.library.research-papers.store',
        'administrators.library.research-papers.update',
        'administrators.notifications.preview',
        'administrators.notifications.store',
        'administrators.roles.assign',
        'administrators.roles.destroy',
        'administrators.roles.edit',
        'administrators.roles.index',
        'administrators.roles.store',
        'administrators.roles.update',
        'administrators.scheduling-analytics.classes.store',
        'administrators.scheduling-analytics.index',
        'administrators.scheduling-analytics.schedules.destroy',
        'administrators.scheduling-analytics.schedules.update',
        'administrators.scheduling-analytics.students.schedule',
        'administrators.scheduling-analytics.students.search',
        'administrators.settings.newsletter.index',
        'administrators.settings.payment-workspace.update',
        'administrators.settings.tuition-adjustment-workspace.update',
        'administrators.settings.update',
        'administrators.students.bulk-destroy',
        'administrators.students.bulk-email',
        'administrators.students.bulk-force-destroy',
        'administrators.students.bulk-manage-clearance',
        'administrators.students.bulk-update-status',
        'administrators.students.change-course',
        'administrators.students.courses.subjects',
        'administrators.students.create',
        'administrators.students.destroy',
        'administrators.students.documents.dynamic.destroy',
        'administrators.students.documents.dynamic.store',
        'administrators.students.documents.fixed.update',
        'administrators.students.documents.index',
        'administrators.students.documents.list',
        'administrators.students.edit',
        'administrators.students.education-school-options',
        'administrators.students.field-values',
        'administrators.students.force-destroy',
        'administrators.students.generate-id',
        'administrators.students.index',
        'administrators.students.link-account',
        'administrators.students.manage-clearance',
        'administrators.students.quick-update',
        'administrators.students.restore',
        'administrators.students.retry-enrollment',
        'administrators.students.show',
        'administrators.students.signature.update',
        'administrators.students.store',
        'administrators.students.subjects.add',
        'administrators.students.subjects.remove',
        'administrators.students.subjects.update-grade',
        'administrators.students.tuition.soa',
        'administrators.students.undo-id-change',
        'administrators.students.update',
        'administrators.students.update-id',
        'administrators.students.update-status',
        'administrators.students.update-tuition',
        'administrators.system-management.academic-calendar.update',
        'administrators.system-management.ai.mcp-servers.destroy',
        'administrators.system-management.ai.mcp-servers.discover',
        'administrators.system-management.ai.mcp-servers.store',
        'administrators.system-management.ai.mcp-servers.update',
        'administrators.system-management.ai.update',
        'administrators.system-management.analytics.update',
        'administrators.system-management.api.update',
        'administrators.system-management.brand.update',
        'administrators.system-management.faculty-fields.destroy',
        'administrators.system-management.faculty-fields.store',
        'administrators.system-management.faculty-fields.update',
        'administrators.system-management.grading.update',
        'administrators.system-management.identifiers.update',
        'administrators.system-management.index',
        'administrators.system-management.notifications.update',
        'administrators.system-management.observability.test',
        'administrators.system-management.observability.update',
        'administrators.system-management.school-details.update',
        'administrators.system-management.school-level.update',
        'administrators.system-management.school.store',
        'administrators.system-management.school.update',
        'administrators.system-management.schools.destroy',
        'administrators.system-management.schools.force-destroy',
        'administrators.system-management.schools.status.update',
        'administrators.system-management.schools.update',
        'administrators.system-management.seo.update',
        'administrators.system-management.socialite.update',
        'administrators.users.create',
        'administrators.users.destroy',
        'administrators.users.edit',
        'administrators.users.impersonate',
        'administrators.users.index',
        'administrators.users.reset-password',
        'administrators.users.stop-impersonating',
        'administrators.users.store',
        'administrators.users.update',
        'administrators.users.verify-email',

        // assessment
        'assessment.download',

        // demo
        'demo.login',

        // download
        'download.attendance-report',
        'download.bulk-assessment-report',
        'download.enrollment-report',
        'download.student-list',
        'download.student-soa',
        'download.timetable-pdf',

        // faculty
        'faculty.action-center.status.update',
        'faculty.classes.attendance.sessions.store',
        'faculty.classes.posts.store',
        'faculty.classes.posts.update',
        'faculty.classes.students.move.accept',
        'faculty.schedule',

        // filament
        'filament.admin.resources.accounts.create',
        'filament.admin.resources.classes.create',
        'filament.admin.resources.classes.edit',
        'filament.admin.resources.classes.index',
        'filament.admin.resources.classes.view',
        'filament.admin.resources.events.view',
        'filament.admin.resources.faculties.create',
        'filament.admin.resources.faculties.edit',
        'filament.admin.resources.faculties.index',
        'filament.admin.resources.faculties.view',
        'filament.admin.resources.student-enrollments.view',
        'filament.admin.resources.students.create',
        'filament.admin.resources.students.edit',
        'filament.admin.resources.students.index',
        'filament.admin.resources.students.view',
        'filament.exports.download',
        'filament.portal.auth.login',

        // finance-documents
        'finance-documents.verify',

        // help
        'help.index',
        'help.reply',
        'help.show',
        'help.store',

        // onboarding
        'onboarding.dismiss',

        // password
        'password.reset',

        // signup
        'signup',

        // social
        'social.auth.redirect',

        // student
        'student.tuition.index',
        'student.tuition.soa',
        'student.tuition.soa.issuances.download',
        'student.tuition.update-requests.index',
    ],
];
