#!/usr/bin/env sh

set -eu

output_file=''
previous=''
url=''
for argument in "$@"; do
    if test "$previous" = '--output'; then
        output_file="$argument"
    fi
    case "$argument" in
        https://github.com/yukazakiri/koakademy/releases/download/*)
            url="$argument"
            ;;
        https://raw.githubusercontent.com/yukazakiri/koakademy/*)
            url="$argument"
            ;;
    esac
    previous="$argument"
done

case "$*" in
    *github.com/yukazakiri/koakademy/releases/download/*)
        test -n "${KOAKADEMY_INSTALLER_TEST_RELEASE_DIR:-}"
        test -n "$output_file"
        asset="${url##*/}"
        cp "$KOAKADEMY_INSTALLER_TEST_RELEASE_DIR/$asset" "$output_file"
        ;;
    *api.github.com/repos/yukazakiri/koakademy/commits/master*)
        printf '{\n  "sha": "%s",\n  "commit": {}\n}\n' \
            "${KOAKADEMY_INSTALLER_TEST_SOURCE_SHA:-0123456789012345678901234567890123456789}"
        ;;
    *raw.githubusercontent.com/yukazakiri/koakademy/*)
        test -n "${KOAKADEMY_INSTALLER_TEST_RELEASE_DIR:-}"
        test -n "$output_file"
        asset="${url##*/}"
        cp "$KOAKADEMY_INSTALLER_TEST_RELEASE_DIR/$asset" "$output_file"
        ;;
    *api.github.com/repos/yukazakiri/koakademy/releases/latest*)
        if test -n "${KOAKADEMY_INSTALLER_TEST_RELEASE_TAG:-}"; then
            printf '{\n  "tag_name": "%s",\n  "draft": false,\n  "prerelease": false\n}\n' \
                "${KOAKADEMY_INSTALLER_TEST_RELEASE_TAG}"
        fi
        ;;
    *github.com/yukazakiri/koakademy/releases/latest*)
        if test -n "${KOAKADEMY_INSTALLER_TEST_RELEASE_TAG:-}"; then
            printf 'https://github.com/yukazakiri/koakademy/releases/tag/%s' \
                "${KOAKADEMY_INSTALLER_TEST_RELEASE_TAG}"
        fi
        ;;
esac
