<?php

/**
 * This file is auto-generated by the Laravel VS Code extension.
 * Do not modify this file directly as your changes will be overwritten.
 */

namespace {

    /**
     * Runs the given closure before each test in the current file.
     *
     * @param-closure-this \PHPUnit\Framework\TestCase|\_Pest\Global\TestCase  $closure
     */
    function beforeEach(?Closure $closure = null): \Pest\PendingCalls\BeforeEachCall {}

    /**
     * Runs the given closure after each test in the current file.
     *
     * @param-closure-this \PHPUnit\Framework\TestCase|\_Pest\Global\TestCase  $closure
     */
    function afterEach(?Closure $closure = null): \Pest\PendingCalls\AfterEachCall {}

    /**
     * Adds the given closure as a test.
     *
     * @param-closure-this \PHPUnit\Framework\TestCase|\_Pest\Global\TestCase  $closure
     */
    function test(?string $description = null, ?Closure $closure = null): \Pest\Support\HigherOrderTapProxy|\Pest\PendingCalls\TestCall {}

    /**
     * Adds the given closure as a test.
     *
     * @param-closure-this \PHPUnit\Framework\TestCase|\_Pest\Global\TestCase  $closure
     */
    function it(string $description, ?Closure $closure = null): \Pest\PendingCalls\TestCall {}

}

namespace _Pest\Global {

    class TestCase {
        use \Pest\Arch\Concerns\Architectable;
    }

}

namespace Pest {

    /**
     * @method self toBeCollection()
     * @method self toBeOne()
     */
    class Expectation {}

}

namespace Pest\Expectations {

    /**
     * @method self toBeCollection()
     * @method self toBeOne()
     */
    class OppositeExpectation {}

}