name: Docker Latest

on:
  workflow_dispatch:
#  push:
#    branches:
#      - 2.x

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to the latest tag
        run: |
          docker buildx build . \
            -f docker/Dockerfile \
            -t ghcr.io/yukazaki/koakademy:latest \
            --platform linux/amd64 \
            --push
